version: '3'  # specify docker-compose version
services: # services means the containers

  bezen:
    build: .  # dockerfile path
    container_name: be-zen
    image: backend:latest # image name
    environment:  # environment variables that passing in the backend Dockerfile
      PORT: 8000
    ports:  # port binding of container to host
      - "8000:8000"